#!/usr/bin/env pwsh

# Executa o PHP Code Sniffer (Pint)
Write-Host "Executando PHP Code Sniffer (Pint)..."
docker exec app ./vendor/bin/pint
if ($LASTEXITCODE -ne 0) {
    Write-Host "Falhas de estilo detectadas. Commit abortado."
    exit 1
}

# Executa os testes com Pest
Write-Host "Executando testes com Pest..."
docker exec app ./vendor/bin/pest
if ($LASTEXITCODE -ne 0) {
    Write-Host "Os testes falharam. Commit abortado."
    exit 1
}

# Análise de código com PHPStan
Write-Host "Analisando o código com PHPStan..."
docker exec app ./vendor/bin/phpstan analyse --memory-limit=2G
if ($LASTEXITCODE -ne 0) {
    Write-Host "Erros de análise encontrados. Commit abortado."
    exit 1
}

Write-Host "Todos os testes e análises foram bem-sucedidos. Prosseguindo com o commit."
